<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ConstantProxy.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConstantProxy.Core\ConstantProxy.Core.csproj" />
    <InternalsVisibleTo Include="ConstantProxy.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.31" />
  </ItemGroup>

</Project>
